name: testAras
on: [push]
jobs:
  test_aras:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  test_aras_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv pip install ./aras_py --system
      - name: Run Python tests
        run: uv run pytest ./aras_py/tests --verbose
